Resources:
  AppSyncApi:
    Type: 'AWS::AppSync::GraphQLApi'
    Properties:
      Name:
        Ref: AppSyncApiName
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        AwsRegion: ap-south-1
        DefaultAction: ALLOW
        UserPoolId: 
          Ref: CognitoUserPoolId
Parameters:
  Stage: 
    Default: dev
    Type: String
  AppSyncApiName:
    Type: String
  AWSRegion:
    Default: 'ap-south-1'
    Type: String
  DynamoDbAccessRole:
    Type: String
  CognitoUserPoolId:
    Type: String