Resources:
  ProductTableDataSource:
    Type: 'AWS::AppSync::DataSource'
    Properties:
      ApiId:
        Fn::GetAtt:
          - AppSyncApi
          - ApiId
      Name: "Products"
      Description: Products Data Source
      Type: AMAZON_DYNAMODB
      ServiceRoleArn:
        Ref: DynamoDbAccessRole
      DynamoDBConfig:
        AwsRegion:
          Ref: AWSRegion
        TableName: 
          Fn::Join: ['-', ['ecommerce', Ref: Stage, 'products']]