Resources:
  GraphQlSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId:
        Fn::GetAtt:
          - AppSyncApi
          - ApiId
      Definition: !Join
        - '\n'
        - - !Sub >-
            file://schemas/userSchema.graphql
          - !Sub >-
            file://schemas/productSchema.graphql