Resources:
  GetAllProductsResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId:
        Fn::GetAtt: AppSyncApi.ApiId
      DataSourceName:
        Fn::GetAtt: ProductTableDataSource.Name
      TypeName: Query
      FieldName: getAllProducts
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": 'Scan'
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result.Items)
    DependsOn: GraphQlSchema
