Resources:
  GetProductTypeListResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId:
        Fn::GetAtt: AppSyncApi.ApiId
      DataSourceName:
        Fn::GetAtt: ProductTableDataSource.Name
      TypeName: Query
      FieldName: getProductTypeList
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": 'Scan'
        }
      ResponseMappingTemplate: |
        #set($result = $ctx.result.Items)
        #set($uniqueTypes = [])
        #foreach($item in $result)
          #if(!$uniqueTypes.contains($item.productType))
            $util.qr($uniqueTypes.add($item.productType))
          #end
        #end
        $util.toJson($uniqueTypes)
    DependsOn: GraphQlSchema