Resources:
  createInventoryResolvers:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId:
        Fn::GetAtt: AppSyncApi.ApiId
      DataSourceName:
        Fn::GetAtt: InventoryTableDataSource.Name
      TypeName: Mutation
      FieldName: createInventory
      RequestMappingTemplate: |
       #set($uuid = $util.autoId())
        {
          "version" : "2017-02-28",
          "operation" : "PutItem",
          "key" : {
            "inventoryId": $util.dynamodb.toDynamoDBJson($uuid)
          },
          #set($args = $util.dynamodb.toMapValues($ctx.args))
          #set( $args.createdAt = $util.dynamodb.toDynamoDB($util.time.nowISO8601()))
          #set( $args.updatedAt = $util.dynamodb.toDynamoDB($util.time.nowISO8601()))
          "attributeValues" : $util.toJson($args)
        }
      ResponseMappingTemplate: |
          $util.toJson($ctx.result)
    DependsOn: GraphQlSchema
